const data = {
    nodes: [
        {
            type: "me",
            uri: "/v2/users/1030",
            name: "Marco Kam",
            imageUrl: "https://nudge.azureedge.net/Image/Person/12218439",
        },
        {
            type: "user",
            uri: "/v2/users/87150",
            name: "Adrienne Radan-Lazic",
            imageUrl: "https://nudge.azureedge.net/Image/Person/30268210",
        },
        {
            type: "user",
            uri: "/v2/users/79286",
            name: "Taylor McGuire",
            imageUrl: "https://nudge.azureedge.net/Image/Person/32522528",
        },
        {
            type: "user",
            uri: "/v2/users/8",
            name: "Paul Teshima",
            imageUrl: "https://nudge.azureedge.net/Image/Person/4979262",
        },
        {
            type: "person",
            uri: "/v2/people/1860",
            name: "Victoria Bull",
            imageUrl: "https://nudge.azureedge.net/Image/Person/32632440",
        },
        {
            type: "person",
            uri: "/v2/people/651060",
            name: "Shawn Williamson",
            imageUrl: "https://nudge.azureedge.net/Image/Person/31891603",
        },
        {
            type: "person",
            uri: "/v2/people/1764",
            name: "Jocelyn Brown",
            imageUrl: "https://nudge.azureedge.net/Image/Person/30266662",
        },
        {
            type: "person",
            uri: "/v2/people/12501046",
            name: "Leah Chapman",
            imageUrl: "https://nudge.azureedge.net/Image/Person/5581931",
        },
        {
            type: "person",
            uri: "/v2/people/1953814",
            name: "Jonathan Tice",
            imageUrl: "https://nudge.azureedge.net/Image/Person/28259919",
        },
        {
            type: "person",
            uri: "/v2/people/118211",
            name: "Kristine Steuart",
            imageUrl: "https://nudge.azureedge.net/Image/Person/28259374",
        },
    ],
    links: [
        { source: "/v2/users/1030", target: "/v2/people/1860", value: 1 },
        { source: "/v2/users/87150", target: "/v2/people/651060", value: 5 },
        { source: "/v2/users/87150", target: "/v2/people/1764", value: 5 },
        { source: "/v2/users/87150", target: "/v2/people/12501046", value: 3 },
        { source: "/v2/users/87150", target: "/v2/people/1860", value: 1 },
        { source: "/v2/users/79286", target: "/v2/people/1953814", value: 1 },
        { source: "/v2/users/79286", target: "/v2/people/1764", value: 5 },
        { source: "/v2/users/8", target: "/v2/people/1764", value: 5 },
        { source: "/v2/users/8", target: "/v2/people/118211", value: 5 },
        { source: "/v2/users/8", target: "/v2/people/1953814", value: 5 },
        { source: "/v2/users/8", target: "/v2/people/1860", value: 5 },
        { source: "/v2/users/8", target: "/v2/people/651060", value: 4 },
    ],
    links2: [
        { source: 0, target: 4, value: 1 },
        { source: 1, target: 5, value: 5 },
        { source: 1, target: 6, value: 5 },
        { source: 1, target: 7, value: 3 },
        { source: 1, target: 4, value: 1 },
        { source: 2, target: 8, value: 1 },
        { source: 2, target: 6, value: 5 },
        { source: 3, target: 6, value: 5 },
        { source: 3, target: 9, value: 5 },
        { source: 3, target: 8, value: 5 },
        { source: 3, target: 4, value: 5 },
        { source: 3, target: 5, value: 4 },
    ],
};